- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    terraform_dir: "./terraform"

  tasks:

    - name: Check if Terraform is installed
      command: terraform version
      register: terraform_version
      ignore_errors: yes

    
    - name: Download Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/1.5.7/terraform_1.5.7_linux_amd64.zip
        dest: /tmp/terraform.zip

    - name: Unzip Terraform locally
      unarchive:
        src: /tmp/terraform.zip
        dest: /tmp/
        remote_src: yes

    - name: Use Terraform from local path
      set_fact:
        terraform_bin: "/tmp/terraform"

    - name: Verify Terraform install
      command: "{{ terraform_bin }} version"

    - name: Initialize Terraform
      command: "{{ terraform_bin }} init"
      args:
        chdir: .

    - name: Apply Terraform
      command: "{{ terraform_bin }} apply -auto-approve"
      args:
        chdir: .

    - name: Get VM IP
      command: "{{ terraform_bin }} output -raw vm_ip"
      register: vm_ip_output
      args:
        chdir: .


    - name: Get VM IP
      command: terraform output -raw vm_ip
      register: vm_ip_output
      args:
        chdir: "{{ terraform_dir }}"

    - name: Show VM IP
      debug:
        msg: "VM deployed with IP: {{ vm_ip_output.stdout }}"

    - name: Add new VM to inventory (temporary)
      add_host:
        name: "{{ vm_ip_output.stdout }}"
        groups: windows

    - name: Add host to inventory
      add_host:
        name: "{{ vm_ip_output.stdout }}"
        groups: windows

