- name: Check Packer Installation
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Check packer version
      ansible.builtin.shell: packer version
      register: packer_check
      ignore_errors: yes

    - name: Show packer version output
      debug:
        var: packer_check.stdout_lines

    - name: Show packer errors (if any)
      debug:
        var: packer_check.stderr_lines