- name: Build Windows Template with Packer
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Run Packer build
      ansible.builtin.command: >
        packer build
        -var "vsphere_user={{ vsphere_user }}"
        -var "vsphere_password={{ vsphere_password }}"
        -var "vsphere_server={{ vsphere_server }}"
        -var "datacenter={{ datacenter }}"
        -var "cluster={{ cluster }}"
        -var "datastore={{ datastore }}"
        -var "network={{ network }}"
        -var "template_name={{ template_name }}-gold"
        -var "vm_cpu={{ vm_cpu }}"
        -var "vm_memory_mb={{ vm_memory_mb }}"
        -var "win_admin_password={{ vm_admin_password }}"
        packer/windows/windows.pkr.hcl
