- name: Configure new VM
  hosts: all
  become: yes

  tasks:
    - name: Ensure system is reachable
      ping:

    - name: Install common packages (Linux example)
      package:
        name: vim
        state: present

- name: Show vSphere env (debug)
  shell: env | grep VSPHERE
  register: vs_env

- debug:
    var: vs_env.stdout_lines

- name: Terraform apply
  command: terraform apply -auto-approve
  environment:
    VSPHERE_SERVER: "{{ vsphere_server }}"
    VSPHERE_USER: "{{ lookup('env','VSPHERE_USER') }}"
    VSPHERE_PASSWORD: "{{ lookup('env','VSPHERE_PASSWORD') }}"