- name: Configure new VM
  hosts: all
  become: yes

  tasks:
    - name: Ensure system is reachable
      ping:

    - name: Install common packages (Linux example)
      package:
        name: vim
        state: present



  provider "vsphere" {
    user                 = var.vsphere_user
    password             = var.vsphere_password
    vsphere_server       = var.vsphere_server
    allow_unverified_ssl = true
  }



- name: Show vSphere env (debug)
  shell: env | grep VSPHERE
  register: vs_env

- debug:
    var: vs_env.stdout_lines
    
- name: Show BOTH env + TF vars
  shell: |
    echo "---- VSPHERE ----"
    env | grep VSPHERE
    echo "---- TF VARS ----"
    env | grep TF_VAR

- name: Show EXACT values being used
  shell: |
    echo "SERVER=$TF_VAR_vsphere_server"
    echo "USER=$TF_VAR_vsphere_user"
    echo "PASS_LENGTH=$(echo -n $TF_VAR_vsphere_password | wc -c)"
  register: tf_debug

- debug:
    var: tf_debug.stdout_lines
 
- name: Show EXACT credentials being passed
  shell: |
    echo "SERVER=$TF_VAR_vsphere_server"
    echo "USER=$TF_VAR_vsphere_user"
    echo "PASS_LEN=$(echo -n $TF_VAR_vsphere_password | wc -c)"


- name: Show EXACT Terraform input values
  shell: |
    echo "SERVER=$TF_VAR_vsphere_server"
    echo "USER=$TF_VAR_vsphere_user"
    echo "PASS_LEN=$(echo -n $TF_VAR_vsphere_password | wc -c)"
  register: tf_vals

- debug:
    var: tf_vals.stdout_lines

- name: Show what Terraform will receive
  shell: |
    echo "TF_VAR_vsphere_server=$TF_VAR_vsphere_server"
    echo "TF_VAR_vsphere_user=$TF_VAR_vsphere_user"
    echo "PASS_LEN=$(echo -n $TF_VAR_vsphere_password | wc -c)"

- name: Terraform apply
  command: terraform apply -auto-approve
  environment:
    TF_VAR_vsphere_server: "{{ vsphere_server }}"
    TF_VAR_vsphere_user: "{{ lookup('env','VSPHERE_USER') }}"
    TF_VAR_vsphere_password: "{{ lookup('env','VSPHERE_PASSWORD') }}"