- name: Build VM with Terraform
  hosts: localhost
  gather_facts: no

  vars:
    terraform_dir: "/runner/project/terraform"
    #terraform_dir: "{{ playbook_dir }}/../../terraform"
    terraform_bin: terraform

  tasks:

    #- name: Show what AWX actually pulled
    #  shell: ls -R /runner/project
    #  register: awx_files

    #- debug:
    #    var: awx_files.stdout_lines

    - name: Terraform init
      command: "{{ terraform_bin }} init"
      args:
        chdir: "{{ terraform_dir }}"

    - name: Show EXACT values being sent to Terraform
      shell: |
        echo "SERVER={{ vsphere_server }}"
        echo "USER=$(echo $VSPHERE_USER)"
        echo "PASS_LEN=$(echo -n $VSPHERE_PASSWORD | wc -c)"
      register: final_debug

    - debug:
        var: final_debug.stdout_lines  


    - name: Test vCenter SDK connectivity
      shell: curl -k https://{{ vsphere_server }}/sdk
      register: sdk_test

    - debug:
        var: sdk_test.stdout_lines
    

    - name: Terraform apply
      command: terraform apply -auto-approve
      args:
        chdir: "/runner/project/terraform"
      environment:
        TF_VAR_vsphere_server: "{{ vsphere_server }}"
        TF_VAR_vsphere_user: "{{ lookup('env','VSPHERE_USER') }}"
        TF_VAR_vsphere_password: "{{ lookup('env','VSPHERE_PASSWORD') }}"
        TF_VAR_vm_name: "{{ vm_name }}"
        TF_VAR_datacenter: "{{ datacenter }}"
        TF_VAR_cluster: "{{ cluster }}"
        TF_VAR_datastore: "{{ datastore }}"
        TF_VAR_network: "{{ network }}"
        TF_VAR_template_name: "{{ template_name }}"

    - name: Get Terraform outputs
      command: "{{ terraform_bin }} output -json"
      args:
        chdir: "{{ terraform_dir }}"
      register: tf_output

    - name: Parse outputs
      set_fact:
        vm_ip: "{{ (tf_output.stdout | from_json).vm_ip.value }}"
        vm_name: "{{ (tf_output.stdout | from_json).vm_name.value }}"

# ----------------------------------------

- name: Configure the new VM
  hosts: localhost
  gather_facts: no

  tasks:
    - name: Wait for WinRM (Windows)
      wait_for:
        host: "{{ vm_ip }}"
        port: 5985
        timeout: 600

    - name: Add host dynamically
      add_host:
        name: new_vm
        ansible_host: "{{ vm_ip }}"
        ansible_user: "{{ vm_admin_user }}"
        ansible_password: "{{ vm_admin_password }}"
        ansible_connection: winrm
        ansible_winrm_transport: ntlm

# ----------------------------------------

- name: Configure VM via Ansible
  hosts: new_vm
  gather_facts: no

  tasks:
    - name: Test connectivity
      win_ping:

    - name: Install IIS
      win_feature:
        name: Web-Server
        state: present